### ISSUE TITLE
A more convenient way to get hidden_states.

### ISSUE THREAD

**Issue by niuzaisheng** [sciai-lab/Truth_is_Universal#1]
Thank you for your very inspiring paper. I noticed that you are using Hook to get the output of each layer when capturing the activation values, in [here](https://github.com/sciai-lab/Truth_is_Universal/blob/8a27364453061b047f7b58db50eb5bd69f51774c/generate_acts.py#L51C1-L56C51). However, the model defined by Huggingface Transformers has a much more convenient way to get the output values for all layers, just by adding output_hidden_states=True:
```
returns = model(input_ids, output_hidden_states=True)
hidden_states = returns.hidden_states
```
The hidden_states will be a list of length L+1, where the 0th element is the output of the embedding layer, and the first element is the output of the 1st DeocderLayer, and so on. You can try to get hidden_states in this way, it will make your method much easier to understand and use, thanks.

**Comment by LennartBuerger** [comment]
Thanks a lot for the suggestion! I did not know this. I am very busy at the moment but once things calm down I will update the code accordingly.
